# Generated by Django 5.0.6 on 2024-07-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.PositiveIntegerField(max_length=2)),
                ('score', models.PositiveIntegerField(max_length=2)),
                ('fairway', models.BooleanField()),
                ('gir', models.BooleanField()),
                ('putts', models.PositiveIntegerField()),
            ],
        ),
    ]
