# Generated by Django 5.0.6 on 2024-07-31 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_hole_hole_alter_hole_putts_alter_hole_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_number', models.IntegerField(max_length=2)),
                ('hole_par', models.IntegerField(choices=[(3, '3'), (4, '4'), (5, '5')], default='4')),
                ('score', models.IntegerField(max_length=2)),
                ('fairway', models.BooleanField()),
                ('gir', models.BooleanField()),
                ('putts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoundModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('course_name', models.CharField(max_length=50)),
                ('tees', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('white', 'White')], default='yellow', max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Hole',
        ),
        migrations.AddField(
            model_name='holemodel',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='stats.roundmodel'),
        ),
    ]
