# Generated by Django 5.0.6 on 2024-08-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_holemodel_roundmodel_delete_hole_holemodel_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmodel',
            name='is_18_holes',
            field=models.BooleanField(default=True),
        ),
    ]
