# Generated by Django 5.0.6 on 2024-08-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_roundmodel_is_18_holes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmodel',
            name='is_front_9',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roundmodel',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
