# Generated by Django 5.0.6 on 2024-08-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_roundmodel_fairways_roundmodel_greens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundmodel',
            name='tees',
            field=models.CharField(choices=[('yellow', 'Yellow'), ('white', 'White'), ('red', 'Red')], default='yellow', max_length=6),
        ),
    ]
